# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
    default: optimism-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

dependencies:
    - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0

# path remapping to support imports from GitHub/NPM
compiler:
    solc:
        version: 0.6.12
        remappings:
            - "openzeppelin-contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0/contracts/"
